### PR TITLE
Source $XDG_CONFIG_DIRS/liquidpromptrc, lowest-priority first (#420)

### PR DESCRIPTION
**Pull request by smcv**
~/.liquidpromptrc is still the highest-priority, and
/etc/liquidpromptrc is still the lowest.

---

Refs #420. This implements the more powerful of the two options: sourcing all the possible places in the search path where we might have a liquidpromptrc. This is potentially useful if you're doing something like putting a host-specific entry in XDG_CONFIG_DIRS ahead of a generic entry.

### CODE REVIEW

**Comment by jcrben** [comment]
Under the XDG standard, I guess I would expect liquidpromptrc to be either inside its own folder or inside the zsh or bash folder.

**Comment by dolmen** [comment]
@aborrero Does Debian have guidelines for this?

**Comment by smcv** [comment]
Closing this PR: there doesn't seem to be a way to tell GitHub that I now want it to be merged into a different branch :-(

I think you'd probably get more mergeable contributions and fewer confused contributors if `master` was the focus of development like it usually is (e.g. in `git` and `linux`).

**Comment by aborrero** [comment]
El 10 feb. 2016 5:49 a. m., "Olivier Mengué" <notifications@github.com>
escribió:
>
> @aborrero Does Debian have guidelines for this?
>

I guess following XDG standards should be fine.
I can't analyze the problem right now (I'm in a conference).

**Comment by smcv** [comment]
> Does Debian have guidelines for this?

<https://wiki.debian.org/UpstreamGuide#User_home_directories> recommends the XDG basedir spec.

**Comment by smcv** [comment]
(See replacement PR, #427 - I couldn't find a way to make github change the branch into which I was asking for a merge.)

**Comment by aborrero** [comment]
Please go ahead. Thanks.

**Pull request closed without merging**
