### PR TITLE
Fix Fossil tag regexp to work on OS X

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by dolmen** [comment]
You forgot to give example of what is incorrecly matched.
Remember that I have to check that your fix will not break on other platforms...

**Comment by nox** [comment]
The I modifier doesn't exist in OS X's sed.

```
± sed s/foo/bar/I
sed: 1: "s/foo/bar/I": bad flag in substitute command: 'I'
```

**Comment by nox** [comment]
And the \w class only exist in extended regular expressions, which flag differs between OS X and GNU.

**Comment by dolmen** [comment]
@nox Do you intend to fix this pull request (use of `_LP_SED_EXTENDED`) and update it (git rebase; git push -f)?

**Comment by dolmen** [comment]
@nox Could you check that my fix in 5c3c6a713a33ddcae08cd970b3bd4996258cc9b3 fixes your issue?

**Comment by nox** [comment]
It does, thank you.

**Comment by milouse** [comment]
Your modification introduces a crash on linux platform. I try to fix it in 6e41ef7e1a2a693795666eb34635c20cb75c2942. Could you both give it a try?

**Comment by dolmen** [comment]
@milouse I've just cherry-picked your patch in the develop branch.

**Pull request closed without merging**
