### PR TITLE
git prompt enhancement if you are currently MERGING, REBASING or CHERRY-PICKING

### PR DESCRIPTION
**Pull request by gro-gg**
This commits adds the information MERGING, REBASING or CHERRY-PICKING after the branch name if your HEAD is in one of these states.

Tested with bash and zsh:

git init
git commit --allow-empty -mm
git checkout -b br1
echo 1 > test
git add .
git commit -mm
git checkout master
git checkout -b br2
echo 2 > test
git add .
git commit -mm

git merge br1
git merge --abort
git rebase br1
git rebase --abort
git cherry-pick br1
git cherry-pick --abort

### CODE REVIEW

**Comment by gro-gg** [comment]
Any news or feedback for this pull request?

**Comment by zbeekman** [comment]
:+1: 

ping @nojhan ?

**Comment by alexprengere** [comment]
I just tried it (meant to do that earlier, sorry). It's awesome! :wink:

Minor detail: you used tabs for indentation, but liquiprompt uses 4 spaces everywhere.

**Comment by gro-gg** [comment]
Fixed and rebased on development

**Comment by dolmen** [comment]
Merged!
Thanks!

**Comment by imagineer64** [comment]
I know this is an old pull request but when I use git rebase -i the prompt has REBASING in it and it doesn't go away unless I restart the bash shell. Has anyone experienced this?

**Comment by gro-gg** [comment]
@imagineer64 Have you finished rebasing with `git rebase --continue` until the last commit is rebased or aborted with `git rebase --abort` ?
If yes, what's the output of `git --version`?

**Comment by Rycieos** [comment]
@imagineer64 this should probably be in a new issue, but...

The relevant code is here:
https://github.com/nojhan/liquidprompt/blob/eda83efe4e0044f880370ed5e92aa7e3fdbef971/liquidprompt#L871-L872

This is the same section that does the untracked files mark, so if that mark (usually a red *) isn't going away either, than something is wrong with the whole prompt updating.

Otherwise, check if the directories in the above check exist. (.git/rebase-apply and .git/rebase-merge). If they persist after the rebase is complete, somehow git is messing up.

**Comment by imagineer64** [comment]
Thanks guys, it went away when I ran git merge - - abort.

**Pull request closed without merging**
