### PR TITLE
Added runtime to zsh prompts

### PR DESCRIPTION
**Pull request by stonewareslord**
Adds runtime for ZSH prompts: 
selection_012

### CODE REVIEW

**Comment by tomvanderlee** [comment]
Yes! I want this!

**Comment by alexprengere** [comment]
Me too! :smiley:

**Comment by stonewareslord** [comment]
Updated.

**Comment by dolmen** [comment]
Please rebase your patch on top of the `develop` branch as documented in [CONTRIBUTING.md](../blob/develop/CONTRIBUTING.md).

**Comment by dolmen** [comment]
Use `git commit --amend` to commit my requested change about the `function` keyword.

**Comment by stonewareslord** [comment]
Updated.

**Comment by dolmen** [comment]
Improved and replaced by #404...

**Pull request closed without merging**
