### PR TITLE
Added Fish shell support

### PR DESCRIPTION
**Pull request by harenome**
Liquidprompt can now be used with [Fish shell](http://fishshell.com/).

### CODE REVIEW

**Comment by nojhan** [comment]
There is now a separate project: https://github.com/wesbarnett/fish-lp

**Comment by dolmen** [comment]
@wesbarnett Have you tried dolmen/angel-PS1? Why did you choose to use the full rewrite of LP in fish?

**Comment by wesbarnett** [comment]
I have not tried angel-PS1, but @Harenome had already done the real work and I just wanted a simple config file to drop into my home folder.

**Comment by Harenome** [comment]
@wesbarnett If I may suggest a few things, I humbly believe you should have forked this differently:
1. Fork the original liquidprompt project so that the projects are related. However this relation would be limited to the GitHub ecosystem...
2. Either:
    1. Create an empty branch and an initial commit...
        ```
        $ git checkout --orphan <newbranch>
        $ git reset --hard
        $ git commit --allow-empty -m "initial commit"
        ```
    2. ...or create a branch from the initial commit.
        ```
        $ git checkout $(git rev-list HEAD | tail -n 1)
        $ git checkout -b <newbranch>
        ```
3. Cherry-pick the commits from this pull request.
4. Cherry-pick your new commits.
5. Delete other branches and push this new branch as your master branch on GitHub.

Your `README.md` would perhaps be a bit more appealing with a screenshot. Also, what about the license?

**Pull request closed without merging**
