### PR TITLE
Option to show only current directory

### PR DESCRIPTION
**Pull request by alexprengere**
Replacement for #329.

### CODE REVIEW

**Comment by alexprengere** [comment]
Any update for this PR?

**Comment by alexprengere** [comment]
Ping

**Comment by alexprengere** [comment]
Ping

**Comment by dolmen** [comment]
Your branch is not rebase on top of the `develop` branch.

I'm also not happy with the option name (LP_CURRENT_DIR_ONLY), but have nothing better for now.
Also some other users use this feature without needing to change the code. See #323.

**Comment by jongiddy** [comment]
Would this be better as a stand-alone variable, separate to the full/shortened path, added similarly to the code in PR #357 ?

**Comment by dolmen** [comment]
I'm not satisfied with the proposed implementation because it has a runtime cost.

Currently a user can already implement the feature himself from his config:
```
LP_ENABLE_SHORTEN_PATH=0
if $_LP_SHELL_bash; then
    LP_PATH_DEFAULT="\\W"
else
    LP_PATH_DEFAULT="%1~"
fi
```
I'm not telling this solution is officially supported. Just that a simple user hack is possible.
So this is the reason why I've not spent much time implementing my ideal implementation of the feature.

**Comment by pkkolos** [comment]
I think there is no need for this PR. You can show only the current directory by setting the variable `LP_PATH_KEEP=-1` as shown in https://github.com/nojhan/liquidprompt/blob/develop/liquidprompt#L616-L619. Admittedly it'd be good if this option is documented.

**Comment by alexprengere** [comment]
I confirm that `LP_ENABLE_SHORTEN_PATH=1` and `LP_PATH_KEEP=-1` will produce the same results as this PR on `bash` and `zsh`.

I have been using using my own fork with this PR for some time now, because keeping more than the current directory took too much space on the prompt. And since I am a `zsh` user, I have the full path in my right prompt anyway :wink:.

But I agree that documenting the `LP_PATH_KEEP=-1` is a better solution than merging this, so if this is alright with you I am thinking of closing the PR.

**Pull request closed without merging**
