### PR TITLE
doc: add installation procedure

### PR DESCRIPTION
**Pull request by monperrus**

### CODE REVIEW

**Comment by dolmen** [comment]
Does Ubuntu/Debian bundles the master branch?

**Comment by Rycieos** [comment]
@aborrero there are now install instructions for Debian/Ubuntu here:
https://liquidprompt.readthedocs.io/en/v2.0.0-beta.2/install/packages.html#debian

Would you want them to include the `liquidprompt_activate` command?

**Comment by aborrero** [comment]
> @aborrero there are now install instructions for Debian/Ubuntu here:
> https://liquidprompt.readthedocs.io/en/v2.0.0-beta.2/install/packages.html#debian
> 
> Would you want them to include the `liquidprompt_activate` command?

sure! why not :-)

You can copy/paste the info from the debian manpage:

```
ACTIVATION
       The liquidprompt package has no way to know which users do you want this prompt to be active for.  A small script, liquidprompt_activate is included to ease activation of the prompt.

       This will set the required environment:

            * The files ~/.bashrc and/or ~/.zshrc are modified to load liquidprompt at startup.
            * If no previous ~/.config/liquidpromptrc file exists, it will be created.

       So, to get liquidprompt working simply run:

            user@debian:~$ liquidprompt_activate
            user@debian:~$ source ~/.bashrc

       Be aware that multiple invocations of the liquidprompt_activate command may pollute ~/.bashrc and/or ~/.zshrc files.
```

**Comment by Rycieos** [comment]
I added bc5eebb6c02d1742a945be13d45ab48a25a9f712 to add those extra details.
You can see the updated documentation here: https://liquidprompt.readthedocs.io/en/latest/install/packages.html#debian

@aborrero if there is any way to make that clearer, please let me know.

@monperrus thanks for bringing this to my attention! Sorry for the delay, we sorely needed better documentation written.

**Comment by monperrus** [comment]
Thanks!

**Pull request closed without merging**
