### PR TITLE
Display git tag, if one is available. (#506)

### PR DESCRIPTION
**Pull request by cburschka**
For #506

### CODE REVIEW

**Comment by Rycieos** [comment]
One issue I see is that there is no way to differentiate between a branch name and a tag name. Since there is no limitation in git to prevent having a tag and a branch named the same thing, this could create confusion with which one is currently checked out.

Git does tell you that you are in a detached head state when checking it out, so as long as one remembers their context they can avoid confusion, but I don't think we should depend on that.

I would suggest adding a "tag: " before the tag name. This is how git does it in `git log`, and it makes it obvious it isn't a branch. Then this would be a feature I would want.

**Comment by LlinksRechts** [comment]
addressed in pr #533

**Comment by nojhan** [comment]
The "tag" text should be configurable with something like LP_MARK_VCS_TAG, and defaults to a shorter unicode character, like u1F516: 🔖.

**Comment by pichi** [comment]
Check out #567 which address also detached tags.

**Comment by Rycieos** [comment]
As commented on https://github.com/nojhan/liquidprompt/issues/506#issuecomment-741997599, this has been added in [v2.0.0-beta.1](https://github.com/nojhan/liquidprompt/releases/tag/v2.0.0-beta.1).

**Pull request closed without merging**
