### PR TITLE
set up LP_ENABLE_ERR to switch non-zero exit reporting on/off

### PR DESCRIPTION
**Pull request by augmentedfourth**
Addresses #543.

### CODE REVIEW

**Comment by augmentedfourth** [comment]
I know that this doesn't explicitly set `LP_ERR=''` if `err != 0` and `LP_ENABLE_ERR` is disabled, but if `LP_ENABLE_ERR` is disabled, `LP_ERR` will never be populated so it won't need to be hidden or returned to an empty string.

**Comment by Rycieos** [comment]
Is there no way to put both of the checks inside the same `if`? That would make it cleaner and possibly faster.

I'm not sure that @dolmen will want to merge this; he has been quite adamant about not adding new config options, especially since this specific case can be done easily through a .ps1 file.

**Comment by augmentedfourth** [comment]
A .ps1 file can remove it entirely? As far as I could tell, that can only change the color.

I tried getting the conditionals merged into a single statement, but since the preferred conditional style throughout has been the double-parentheses I couldn't get it to work. I can definitely make it work with square brackets, but was trying to maintain consistency.

**Comment by augmentedfourth** [comment]
Ah, got it. @atsaloli, is this solution OK for you?

**Comment by atsaloli** [comment]
Works beautifully!  Thank you!  :+1: :heart: :fireworks: :unicorn: :shell:

**Comment by atsaloli** [comment]
Actually, my prompt is broken now in that it no longer shows the path of the working directory.

**Comment by atsaloli** [comment]
And sorry I took a while to reply... I've been traveling.  =)   (That's also why I did not dig into it myself like you suggested.)

**Comment by augmentedfourth** [comment]
If all you've changed from the default is to remove the error message, line 44 of `liquid.ps1` should say:

`LP_PS1="${LP_PS1}${LP_RUNTIME}${LP_MARK_PREFIX}${LP_MARK}${LP_PS1_POSTFIX}"`

Has anything else changed from the release version of `liquid.ps1`?

**Comment by atsaloli** [comment]
I applied the diff in this pull request, which updated two files:  liquidprompt, and liquidpromptrc-dist

It's been working fine ever since, just the path froze in the prompt originally right after the change (i.e., wouldn't update even if I changed dirs).  It works fine now, I've been using it nearly every day. I've been telling my friends about it too.  =)  Good stuff!

**Comment by augmentedfourth** [comment]
As @Rycieos noted, this pull request won't be merged because it adds a new option to `.liquidpromptrc` and that's become frowned upon (I wasn't aware of that when I submitted this). You're free to keep this diff applied to your local copy, but you'll need to rebase the change if you want to get new official updates. Apparently the "official" answer is to edit your `.ps1` theme file to not include `${LP_ERR}` in the prompt definition, unless that actually doesn't address your concern somehow.

**Comment by atsaloli** [comment]
Well! OK, thank you.  =)

**Comment by atsaloli** [comment]
I set up a custom ps1 theme file, and edited it to remove LP_ERR and reverted the liquidprompt bash code back to master.  Works great, thanks!

**Pull request closed without merging**
