### PR TITLE
Add untracked marker for SVN repos

### PR DESCRIPTION
**Pull request by jonathanjsimon**
I used the same marker as the Git untracked marker for simplicity

### CODE REVIEW

**Comment by jonathanjsimon** [comment]
I also added ignore lines starting with X (for SVN ignore) to the changes count

**Comment by dolmen** [comment]
Could you rebase (did your read CONTRIBUTING.md?) your work on top of develop and squash all your commits as just one:
```
git remote add upstream git://github.com/nojhan/liquidprompt.git
git remote update
git checkout master
git rebase develop
# Make a backup
git branch master master.bakup
git squash -i upstream/develop
# Mark all the commits except the first one as 'squash' instead of 'pick' and save
git log # to check what happened
# If good...
git push -f
```

Some doc about squashing: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by jonathanjsimon** [comment]
I didn't read CONTRIBUTING.md (sorry, first pull request ever, just sorta went for it) but I will and I'll get this done probably this evening. Thanks.

**Comment by jonathanjsimon** [comment]
@dolmen So that didn't go as expected. I'll checkout develop and just do it there. Sorry for the trouble.

**Pull request closed without merging**
