### PR TITLE
Allow the colon to be customized

### PR DESCRIPTION
**Pull request by pgarrison**
Now your lambda or arrow can take over the role of the colon.

Replaces #428

### CODE REVIEW

**Comment by pgarrison** [comment]
I believe this is ready to be merged

**Comment by dolmen** [comment]
Please fix the commit comment: it says "Conflict: liquidprompt".
Use `git commit --amend` and `git rebase && git push -f`.

**Comment by dolmen** [comment]
An entry must also be added in `liquidpromptrc-dist`.

**Comment by pgarrison** [comment]
All cleaned up

**Comment by dolmen** [comment]
Merged. Thanks!

**Pull request closed without merging**
